### ISSUE TITLE
Add collapsable item list/menu with slot expanded content

### ISSUE THREAD

**Issue by kingy04** [CroudTech/Croud-Style-Guide#78]
**User Stories:**
As a user i would like to see a expandable/collapsable item with some relevant content within

**Requirements:**
Create a new style component for the above with props for the item header text and a slot for the content within it

**Comment by BrockReece** [comment]
I think this could be split into two different components. As I don't think an Accordion style component is flexible enough for what you need on the gantt chart.

- Toggle Header component
- Accordion style component using this the Toggle Header

Let me know if you want to discuss this?

**Comment by kingy04** [comment]
Thats along the lines i was thinking of going, quite atomic.

**Comment by kingy04** [comment]
This was translated into the toggle-header https://croudtech.github.io/Croud-Style-Guide/technical/#croud-toggle-header

Closing
